express/config/routes.rb
Express::Application.routes.draw do
  get "ship_order/index"

  post "ship_order/insert_sender"
  post "ship_order/insert_receiver"
  post "ship_order/create_order"

  resources :orders

  resources :contacters

  match '/ship_order/insert_sender' => "ShipOrder#insert_sender"
  match '/ship_order/insert_receiver' => "ShipOrder#insert_receiver"
  match '/ship_order/create_order' => "ShipOrder#create_order"
end

express/app/models/contacter.rb
class Contacter < ActiveRecord::Base
  attr_accessible :addressRegion, :cellphoneNum, :company, :contactNum, :contacterName, :detailedAddress, :email, :postalCode, :validFlag
end

express/app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :charge, :estimateTermDate, :expressNum, :expressProvider, :orderContent, :orderDate, :orderDispNum, :orderState, :paymentType, :posterID, :posterNote, :receiverID, :senderID, :servicePoints, :serviceProcess, :serviceSuggest, :shipmentType, :specialHandling, :specialOffer, :userNote, :volume, :weight
  def set_user_data
    @porterID = 'test'
  end
  def init_new_order
    @userNote = 'test'
  end
end

express/app/models/temp_order.rb
class TempOrder
  attr_reader :title, :sender ,:receiver ,:order
  def initialize
    @order = Order.new
    @sender = 0
    @receiver = 0
  end
  def get_sender
    return @sender
  end
  def set_sender(id)
    @sender = id
    @order.senderID = id
  end
  def get_receiver
    return @receiver
  end
  def set_receiver(id)
    @receiver = id
    @order.receiverID = id
  end
  def get_order
      return @order
  end
end

express/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

express/app/controllers/contacters_controller.rb
class ContactersController < ApplicationController
  # GET /contacters
  # GET /contacters.json
  def index
    @contacters = Contacter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacters }
    end
  end

  # GET /contacters/1
  # GET /contacters/1.json
  def show
    @contacter = Contacter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contacter }
    end
  end

  # GET /contacters/new
  # GET /contacters/new.json
  def new
    @contacter = Contacter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contacter }
    end
  end

  # GET /contacters/1/edit
  def edit
    @contacter = Contacter.find(params[:id])
  end

  # POST /contacters
  # POST /contacters.json
  def create
    @contacter = Contacter.new(params[:contacter])

    respond_to do |format|
      if @contacter.save
        format.html { redirect_to @contacter, notice: 'Contacter was successfully created.' }
        format.json { render json: @contacter, status: :created, location: @contacter }
      else
        format.html { render action: "new" }
        format.json { render json: @contacter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacters/1
  # PUT /contacters/1.json
  def update
    @contacter = Contacter.find(params[:id])

    respond_to do |format|
      if @contacter.update_attributes(params[:contacter])
        format.html { redirect_to @contacter, notice: 'Contacter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contacter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacters/1
  # DELETE /contacters/1.json
  def destroy
    @contacter = Contacter.find(params[:id])
    @contacter.destroy

    respond_to do |format|
      format.html { redirect_to contacters_url }
      format.json { head :no_content }
    end
  end
end

express/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
 # attr_reader :sender , :receiver
  cattr_accessor :receiver,:sender

  def initialize
    receiver = Contacter.find_all_by_id('3')
    sender = Contacter.find_all_by_id('3')
  end
  def index
    @orders = Order.all

    sender = Contacter.find_all_by_id('3')
    @senderTmp = sender
    receiver = Contacter.find_all_by_id('2')
    @receiverTmp = receiver

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end
  def  insert_sender
    sender = Contacter.find_all_by_id('2')
    @senderTmp = sender
    print Time.now
  end
  def insert_receiver
    receiver = Contacter.find_all_by_id('2')
    @receiverTmp = receiver

  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new
    @contacters = Contacter.all

    if sender.nil?
      sender = Contacter.find_all_by_id('1')
    end
    if receiver.nil?
      receiver = Contacter.find_all_by_id('2')
    end

    @senderTmp = sender
    @receiverTmp = receiver

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

express/app/controllers/ship_order_controller.rb
class ShipOrderController < ApplicationController
  def initialize

  end
  def index
      @temp_order = find_session
      @contacters = Contacter.all;
      #get send msg id
      @id = @temp_order.get_sender
      if @id == 0
        @sender = Contacter.new
      else
        @sender = Contacter.find_all_by_id(@id)
      end
      #get receiver msg id
      @id = @temp_order.get_receiver
      if @id == 0
        @receiver = Contacter.new
      else
        @receiver = Contacter.find_all_by_id(@id)
      end
      #get order msg
      @order = @temp_order.get_order
      init_new_order(@order)

  end

  def insert_sender
    @temp_order = find_session
    @temp_order.set_sender(params[:id])
    redirect_to('/ship_order/index')
  end

  def insert_receiver
    @temp_order = find_session
    @temp_order.set_receiver(params[:id])
    @receiver= Contacter.find_all_by_id(  @temp_order.get_receiver )
    redirect_to('/ship_order/index')
  end


  private
  def find_session
    session[:temp_order] ||= TempOrder.new
    return session[:temp_order]
  end
  def init_new_order(test)
    test.posterID= '0'
    test.userNote= 'fuck you'
  end
  def create_order
    @temp_order = find_session

    @id = @temp_order.get_sender
    if @id == 0
      @sender = Contacter.new
    else
      @sender = Contacter.find_all_by_id(@id)
    end
    @sender.save
  end

end

express/app/helpers/application_helper.rb
module ApplicationHelper
end

express/app/helpers/contacters_helper.rb
module ContactersHelper
end

express/app/helpers/orders_helper.rb
module OrdersHelper
end

express/app/helpers/ship_order_helper.rb
module ShipOrderHelper
end

express/app/views/contacters/_form.html.erb
<%= form_for(@contacter) do |f| %>
  <% if @contacter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contacter.errors.count, "error") %> prohibited this contacter from being saved:</h2>

      <ul>
      <% @contacter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contacterName %><br />
    <%= f.text_field :contacterName %>
  </div>
  <div class="field">
    <%= f.label :addressRegion %><br />
    <%= f.text_field :addressRegion %>
  </div>
  <div class="field">
    <%= f.label :detailedAddress %><br />
    <%= f.text_field :detailedAddress %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :contactNum %><br />
    <%= f.text_field :contactNum %>
  </div>
  <div class="field">
    <%= f.label :cellphoneNum %><br />
    <%= f.text_field :cellphoneNum %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :postalCode %><br />
    <%= f.number_field :postalCode %>
  </div>
  <div class="field">
    <%= f.label :validFlag %><br />
    <%= f.number_field :validFlag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

express/app/views/contacters/edit.html.erb
<h1>Editing contacter</h1>

<%= render 'form' %>

<%= link_to 'Show', @contacter %> |
<%= link_to 'Back', contacters_path %>

express/app/views/contacters/index.html.erb
<h1>Listing contacters</h1>

<table>
  <tr>
    <th>Contactername</th>
    <th>Addressregion</th>
    <th>Detailedaddress</th>
    <th>Company</th>
    <th>Contactnum</th>
    <th>Cellphonenum</th>
    <th>Email</th>
    <th>Postalcode</th>
    <th>Validflag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacters.each do |contacter| %>
  <tr>
    <td><%= contacter.contacterName %></td>
    <td><%= contacter.addressRegion %></td>
    <td><%= contacter.detailedAddress %></td>
    <td><%= contacter.company %></td>
    <td><%= contacter.contactNum %></td>
    <td><%= contacter.cellphoneNum %></td>
    <td><%= contacter.email %></td>
    <td><%= contacter.postalCode %></td>
    <td><%= contacter.validFlag %></td>
    <td><%= link_to 'Show', contacter %></td>
    <td><%= link_to 'Edit', edit_contacter_path(contacter) %></td>
    <td><%= link_to 'Destroy', contacter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contacter', new_contacter_path %>

express/app/views/contacters/new.html.erb
<h1>New contacter</h1>

<%= render 'form' %>

<%= link_to 'Back', contacters_path %>

express/app/views/contacters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contactername:</b>
  <%= @contacter.contacterName %>
</p>

<p>
  <b>Addressregion:</b>
  <%= @contacter.addressRegion %>
</p>

<p>
  <b>Detailedaddress:</b>
  <%= @contacter.detailedAddress %>
</p>

<p>
  <b>Company:</b>
  <%= @contacter.company %>
</p>

<p>
  <b>Contactnum:</b>
  <%= @contacter.contactNum %>
</p>

<p>
  <b>Cellphonenum:</b>
  <%= @contacter.cellphoneNum %>
</p>

<p>
  <b>Email:</b>
  <%= @contacter.email %>
</p>

<p>
  <b>Postalcode:</b>
  <%= @contacter.postalCode %>
</p>

<p>
  <b>Validflag:</b>
  <%= @contacter.validFlag %>
</p>


<%= link_to 'Edit', edit_contacter_path(@contacter) %> |
<%= link_to 'Back', contacters_path %>

express/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Express</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

express/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

          <ul>
            <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :'订单号码' %><br />
      <%= f.text_field :orderDispNum %>
    </div>
    <div class="field">
      <%= f.label :'订单状态' %><br />
      <%= f.number_field :orderState %>
    </div>
    <div class="field">
      <%= f.label :'运单号码' %><br />
      <%= f.text_field :expressNum %>
    </div>
    <div class="field">
      <%= f.label :'发送人' %><br />
      <%= f.number_field :senderID %>
    </div>
    <div class="field">
      <%= f.label :'收件人' %>
      <%= f.number_field :receiverID %>
    </div>
    <div class="field">
      <%= f.label :'下单时间' %>
      <%= f.datetime_select :orderDate %>
    </div>
    <div class="field">
      <%= f.label :'快递RAW' %>
      <%= f.text_field :orderContent %>
    </div>
    <div class="field">
      <%= f.label :'快递员' %>
      <%= f.number_field :posterID %>
    </div>
    <div class="field">
      <%= f.label :'预计时间' %>
      <%= f.datetime_select :estimateTermDate %>
    </div>
    <div class="field">
      <%= f.label :'发送人' %>
      <%= f.text_field :servicePoints %>
    </div>
    <div class="field">
      <%= f.label :'用户反馈' %>
      <%= f.text_field :serviceSuggest %>
    </div>
    <div class="field">
      <%= f.label :'服务进度' %>
      <%= f.text_field :serviceProcess %>
    </div>
    <div class="field">
      <%= f.label :'服务商' %>
      <%= f.number_field :expressProvider %>
    </div>
    <div class="field">
      <%= f.label :'服务类型' %>
      <%= f.number_field :shipmentType %>
    </div>
    <div class="field">
      <%= f.label :'退件处理' %>
      <%= f.text_field :specialHandling %>
    </div>
    <div class="field">
      <%= f.label :'支付方式' %>
      <%= f.number_field :paymentType %>
    </div>
    <div class="field">
      <%= f.label :'特殊服务' %>
      <%= f.text_field :specialOffer %>
    </div>
    <div class="field">
      <%= f.label :'用户备注' %>
      <%= f.text_area :userNote %>
    </div>
    <div class="field">
      <%= f.label :'快递员备注' %>
      <%= f.text_field :posterNote %>
    </div>
    <div class="field">
      <%= f.label :'重量' %>
      <%= f.number_field :weight %>
    </div>
    <div class="field">
      <%= f.label :'体积' %>
      <%= f.text_field :volume %>
    </div>
    <div class="field">
      <%= f.label :'运费' %>
      <%= f.number_field :charge %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

express/app/views/orders/_list_contacters.html.erb
<table>
  <tr>
    <th>Contactername</th>
    <th>Addressregion</th>
    <th>Detailedaddress</th>
    <th>Company</th>
    <th>Contactnum</th>
    <th>Cellphonenum</th>
    <th>Email</th>
    <th>Postalcode</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @contacters.each do |contacter| %>
      <tr>
        <td><%= contacter.contacterName %></td>
        <td><%= contacter.addressRegion %></td>
        <td><%= contacter.detailedAddress %></td>
        <td><%= contacter.company %></td>
        <td><%= contacter.contactNum %></td>
        <td><%= contacter.cellphoneNum %></td>
        <td><%= contacter.email %></td>
        <td><%= contacter.postalCode %></td>
        <td><%= button_to '插入发件人', :action => "insert_sender"  %></td>
        <td><%= button_to '插入收件人'  %></td>
        <td><%= link_to '编辑', edit_contacter_path(contacter) %></td>
        <td><%= link_to '删除', contacter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

express/app/views/orders/_show_receiver.html.erb
<%= form_for(@receiverTmp) do |f| %>
    <div class="field">
      <%= f.label '姓名' %> <%= f.text_field :contacterName %>
    </div>
    <div class="field">
      <%= f.label '地区' %>
      <%= f.text_field :addressRegion %>
    </div>
    <div class="field">
      <%= f.label '地址' %>
      <%= f.text_field :detailedAddress %>
    </div>
    <div class="field">
      <%= f.label '公司' %>
      <%= f.text_field :company %>
    </div>
    <div class="field">
      <%= f.label '电话' %>
      <%= f.text_field :contactNum %>
    </div>
    <div class="field">
      <%= f.label '手机' %>
      <%= f.text_field :cellphoneNum %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label '邮编' %>
      <%= f.number_field :postalCode %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

express/app/views/orders/_show_sender.html.erb
<%= form_for(@senderTmp) do |f| %>


    <div class="field">
      <%= f.label '姓名' %> <%= f.text_field :contacterName %>
    </div>
    <div class="field">
      <%= f.label '地区' %>
      <%= f.text_field :addressRegion %>
    </div>
    <div class="field">
      <%= f.label '地址' %>
      <%= f.text_field :detailedAddress %>
    </div>
    <div class="field">
      <%= f.label '公司' %>
      <%= f.text_field :company %>
    </div>
    <div class="field">
      <%= f.label '电话' %>
      <%= f.text_field :contactNum %>
    </div>
    <div class="field">
      <%= f.label '手机' %>
      <%= f.text_field :cellphoneNum %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label '邮编' %>
      <%= f.number_field :postalCode %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

express/app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

express/app/views/orders/index.html.erb
<h1>Listing orders</h1>
<p></p>


<p></p>
<p></p>
<p></p>

<table>
  <tr>
    <th>Orderdispnum</th>
    <th>Orderstate</th>
    <th>Expressnum</th>
    <th>Senderid</th>
    <th>Receiverid</th>
    <th>Orderdate</th>
    <th>Ordercontent</th>
    <th>Posterid</th>
    <th>Estimatetermdate</th>
    <th>Servicepoints</th>
    <th>Servicesuggest</th>
    <th>Serviceprocess</th>
    <th>Expressprovider</th>
    <th>Shipmenttype</th>
    <th>Specialhandling</th>
    <th>Paymenttype</th>
    <th>Specialoffer</th>
    <th>Usernote</th>
    <th>Posternote</th>
    <th>Weight</th>
    <th>Volume</th>
    <th>Charge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.orderDispNum %></td>
    <td><%= order.orderState %></td>
    <td><%= order.expressNum %></td>
    <td><%= order.senderID %></td>
    <td><%= order.receiverID %></td>
    <td><%= order.orderDate %></td>
    <td><%= order.orderContent %></td>
    <td><%= order.posterID %></td>
    <td><%= order.estimateTermDate %></td>
    <td><%= order.servicePoints %></td>
    <td><%= order.serviceSuggest %></td>
    <td><%= order.serviceProcess %></td>
    <td><%= order.expressProvider %></td>
    <td><%= order.shipmentType %></td>
    <td><%= order.specialHandling %></td>
    <td><%= order.paymentType %></td>
    <td><%= order.specialOffer %></td>
    <td><%= order.userNote %></td>
    <td><%= order.posterNote %></td>
    <td><%= order.weight %></td>
    <td><%= order.volume %></td>
    <td><%= order.charge %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

express/app/views/orders/new.html.erb
<h1>New order</h1>
<%= render 'form' %>
<%= link_to 'Back', orders_path %>

express/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Orderdispnum:</b>
  <%= @order.orderDispNum %>
</p>

<p>
  <b>Orderstate:</b>
  <%= @order.orderState %>
</p>

<p>
  <b>Expressnum:</b>
  <%= @order.expressNum %>
</p>

<p>
  <b>Senderid:</b>
  <%= @order.senderID %>
</p>

<p>
  <b>Receiverid:</b>
  <%= @order.receiverID %>
</p>

<p>
  <b>Orderdate:</b>
  <%= @order.orderDate %>
</p>

<p>
  <b>Ordercontent:</b>
  <%= @order.orderContent %>
</p>

<p>
  <b>Posterid:</b>
  <%= @order.posterID %>
</p>

<p>
  <b>Estimatetermdate:</b>
  <%= @order.estimateTermDate %>
</p>

<p>
  <b>Servicepoints:</b>
  <%= @order.servicePoints %>
</p>

<p>
  <b>Servicesuggest:</b>
  <%= @order.serviceSuggest %>
</p>

<p>
  <b>Serviceprocess:</b>
  <%= @order.serviceProcess %>
</p>

<p>
  <b>Expressprovider:</b>
  <%= @order.expressProvider %>
</p>

<p>
  <b>Shipmenttype:</b>
  <%= @order.shipmentType %>
</p>

<p>
  <b>Specialhandling:</b>
  <%= @order.specialHandling %>
</p>

<p>
  <b>Paymenttype:</b>
  <%= @order.paymentType %>
</p>

<p>
  <b>Specialoffer:</b>
  <%= @order.specialOffer %>
</p>

<p>
  <b>Usernote:</b>
  <%= @order.userNote %>
</p>

<p>
  <b>Posternote:</b>
  <%= @order.posterNote %>
</p>

<p>
  <b>Weight:</b>
  <%= @order.weight %>
</p>

<p>
  <b>Volume:</b>
  <%= @order.volume %>
</p>

<p>
  <b>Charge:</b>
  <%= @order.charge %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

express/app/views/ship_order/_list_contacters.html.erb
<table>
  <tr>
    <th>姓名</th>
    <th>区域</th>
    <th>地区</th>
    <th>公司</th>
    <th>电话</th>
    <th>手机</th>
    <th>Email</th>
    <th>邮编</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @contacters.each do |contacter| %>
      <tr>
        <td><%= contacter.contacterName %></td>
        <td><%= contacter.addressRegion %></td>
        <td><%= contacter.detailedAddress %></td>
        <td><%= contacter.company %></td>
        <td><%= contacter.contactNum %></td>
        <td><%= contacter.cellphoneNum %></td>
        <td><%= contacter.email %></td>
        <td><%= contacter.postalCode %></td>
        <td><%= button_to '插入发件人', :action => "insert_sender",:id => contacter.id  %></td>
        <td><%= button_to '插入收件人' , :action => "insert_receiver",:id => contacter.id %></td>
        <td><%= link_to '编辑', edit_contacter_path(contacter) %></td>
        <td><%= link_to '删除', contacter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

express/app/views/ship_order/_show_contacter.html.erb
<%= form_for(contact) do |f| %>

    <div class="field">
      <%= f.label '姓名' %> <%= f.text_field :contacterName %>
    </div>
    <div class="field">
      <%= f.label '地区' %>
      <%= f.text_field :addressRegion %>
    </div>
    <div class="field">
      <%= f.label '地址' %>
      <%= f.text_field :detailedAddress %>
    </div>
    <div class="field">
      <%= f.label '公司' %>
      <%= f.text_field :company %>
    </div>
    <div class="field">
      <%= f.label '电话' %>
      <%= f.text_field :contactNum %>
    </div>
    <div class="field">
      <%= f.label '手机' %>
      <%= f.text_field :cellphoneNum %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label '邮编' %>
      <%= f.text_field :postalCode %>
    </div>
    <div class="actions">
      <%= f.submit :value => '保存'%>
    </div>
<% end %>

express/app/views/ship_order/create_order.html.erb
<h1>订单确认</h1>
<%= @temp_order %>
<p>test--></p>
<%= @test%>
<%= %>
<div>
    <%= link_to 'Back', '/ship_order/index' %>
</div>

express/app/views/ship_order/index.html.erb
<title>订单生成</title>

<body>
    <h1>订单生成</h1>
    <div id="list_contacter">
        <%= render 'list_contacters' %>
    </div>

    <p></p>
    <div id="show_order">
      <%= render :partial =>  "show_order"  , :locals  => {:object => @order,:as => :test}  %>
    </div>
    <p>发件人</p>
    <div id="show_sender">
        <%= render :partial =>  "show_contacter" , :locals  => {:contact => @sender} %>
    </div>
    <p>收件人</p>
    <div id="show_recevier">
        <%= render :partial =>  "show_contacter" , :locals  => {:contact => @receiver} %>
    </div>
    <%= button_to '生成订单',:action => 'create_order' %>

</body>

express/app/views/ship_order/insert_sender.html.erb
<h1>ShipOrder#insert_sender</h1>
<p>Find me in app/views/ship_order/insert_sender.html.erb</p>

<%= render 'show_sender'%>
<p><%= link_to 'Back', '/ship_order/index' %></p>